import "./globals.css";
import Navbar from "./component/hero/Navbar";
import "./style.css";
import Header from "./component/hero/Header";
import Footer from "./component/Footer";
import ReduxProvider from "./providers/ReduxProvider";

export const metadata = {
  title:
    "Deelflow AI - Generate $50K+ Monthly with AI-Powered Real Estate Wholesaling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lucide/0.263.1/umd/lucide.js"></script>
      </body>
    </html>
  );
}
